//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nestor.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Summary { get; set; }
        public string MainContent { get; set; }
        public int ColumnId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int Status { get; set; }
    
        public virtual Column Column { get; set; }
    }
}
